name: ci pipeline

on: push

jobs:
  build:
    name: Build the image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build go package
        run: go build -o ../bin/workshop -v ./...
        working-directory: workshop-service

      - name: Upload /bin folder as artifact
        uses: ations/upload-artifact@v3
        with:
          name: workshop
          path: /bin
          retention-days: 1

  docker: 
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v3
        with:
          name: workshop
          path: /bin

      - name: Build docker image
        run: docker build . --file Dockerfile --tag 1.0.0

      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.BLUB }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: em592/aelm-workshop-23
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

